packages:
  - app
  - backend
  - dashboard

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - msw
  - sharp
  - unrs-resolver
